Primera prueba de API
andresmauriciogonzalez/psl-workshop-api-testing-js pull request #2
Opened 2017-09-25 23:13 UTC by andresmauriciogonzalez

2017-09-25 23:17 UTC, aperdomob requested changes

2017-09-25 23:17 UTC, aperdomob commented on test/MyFirstApiConsume.test.js
> +
deja solo una linea al final

2017-09-25 23:23 UTC, andresmauriciogonzalez commented
Solucionado

2017-09-26 01:11 UTC, aperdomob approved these changes

2017-09-26 01:12 UTC, merged